### ISSUE TITLE
Getting error on sign in with twitter

### ISSUE THREAD

**Issue by glockjt** [dreyacosta/postit#4]
500 failed to obtain access token (Error: read ECONNRESET)

Any idea what could be wrong?

**Comment by dreyacosta** [comment]
Have you set your Twitter keys on routes/config.js?

twitter: {
    consumerKey: 'xxx',
    consumerSecret: 'xxx'
},

**Comment by glockjt** [comment]
Yes i did, i think it ended up being something with my install of node.  I
re-installed it and it seems to fix the issue.  Sorry for not closing this
post earlier.
